### ISSUE TITLE
Can this error message be improved on?

### ISSUE THREAD

**Issue by jpmens** [jedisct1/piknik#6]
I had a 0.4 `piknik -server` running and ran `piknik` to make sure the version (0.5) I downloaded matched my architecture before copying over the binary:

```
piknik
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x8201960, 0x1850a010)
	/home/travis/.gimme/versions/go1.6.3.linux.amd64/src/runtime/panic.go:481 +0x326
main.(*Client).pasteOperation(0x18531cc0, 0x1854e251, 0x20, 0x20, 0x0)
	/home/travis/gopath/src/github.com/jedisct1/piknik/client.go:100 +0x143f
main.RunClient(0x8237100, 0xe, 0x1850e410, 0xc, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/jedisct1/piknik/client.go:170 +0xd68
main.main()
	/home/travis/gopath/src/github.com/jedisct1/piknik/piknik.go:167 +0xf15
```

It _then_ dawned on me that this is probably due to a running server ...

**Comment by jedisct1** [comment]
I think this has been fixed since.

**Comment by jedisct1** [comment]
And a87883760d34aef7d2631422107d19908885fd0a should improve this at other places.

Thanks!
